# Generated by Django 3.1.7 on 2021-03-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feet',
            options={'verbose_name_plural': 'Feet'},
        ),
        migrations.AlterModelOptions(
            name='legs',
            options={'verbose_name_plural': 'Legs'},
        ),
        migrations.AlterModelOptions(
            name='tables',
            options={'verbose_name_plural': 'Table'},
        ),
        migrations.AlterField(
            model_name='legs',
            name='size',
            field=models.IntegerField(verbose_name='size (in cm)'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='feet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.feet', verbose_name='feet_id'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='legs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.legs', verbose_name='leg_id'),
        ),
    ]
